#!/usr/bin/env bash

find -mindepth 2                \
     -maxdepth 2                \
     -type f                    \
     -name '*.rkt'              \
     ! -name 'common.rkt'       \
     -exec raco test            \
                --heartbeat     \
                --table         \
                {} +
