#!/usr/bin/env bash

find .                          \
     -type f                    \
     -name '*.rkt'              \
     ! -name 'common.rkt'       \
     ! -name 'harness.rkt'      \
     -exec raco test            \
                --heartbeat     \
                --table         \
                {} +
