#lang racket
(provide (all-defined-out))

;;; requirements
(require xrepl)
(require racket/trace)
(require rackunit "../src/interpreter.rkt")
(require "common.rkt")


;;; tests

(assert (test-interpret "given-files/1") 150)
(assert (test-interpret "given-files/2") -4)
(assert (test-interpret "given-files/3") 10)
(assert (test-interpret "given-files/4") 16)
(assert (test-interpret "given-files/5") 220)
(assert (test-interpret "given-files/6") 5)
(assert (test-interpret "given-files/7") 6)
(assert (test-interpret "given-files/8") 10)
(assert (test-interpret "given-files/9") 5)
(assert (test-interpret "given-files/10") -39)
(assert-interpret-err "given-files/11" 'assign-before-declare)
(assert-interpret-err "given-files/12" 'illegal-var-dereferencing)
(assert-interpret-err "given-files/13" 'illegal-var-dereferencing)
(assert-interpret-err "given-files/14" 'illegal-var-use)
(assert (test-interpret "given-files/15") 'true)
(assert (test-interpret "given-files/16") 100)
(assert (test-interpret "given-files/17") 'false)
(assert (test-interpret "given-files/18") 'true)
(assert (test-interpret "given-files/19") 128)
(assert (test-interpret "given-files/20") 12)
(assert (test-interpret "given-files/21") 30)
(assert (test-interpret "given-files/22") 11)
(assert (test-interpret "given-files/23") 1106)
(assert (test-interpret "given-files/24") 12 "state in op")
(assert (test-interpret "given-files/25") 16)
(assert (test-interpret "given-files/26") 72)
(assert (test-interpret "given-files/27") 21)
(assert (test-interpret "given-files/28")  164)
