#! /usr/bin/env bash

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]] ; then
    printf \
"Test harness for Scheme unit tests.
Usage: ./run-tests <test_file>\n"
    exit 0
elif [[ -z ${1+x} ]] ; then                     # no args
    printf "Must supply test_file!\n"
    exit 1
elif [[ -z ${2+x} ]] ; then                     # only 1
    test_name="${1///}"
    test_file="$test_name/$test_name.rkt"
    raco test --heartbeat "$test_file"
# else                                            # one and two
#     test_file="$1"

#     if [[ -z ${3+x} ]] ; then
#         test_case="$2"
#     else
#         test_case="$(seq -s " " $2 $3)"
#     fi
#     test_case_arg="'($test_case)"

#     racket -e "(require \"$test_file\")
#                (require rackunit \"../src/interpreter.rkt\")
#                (require \"common.rkt\")
#                (display \"\n\")
#                (display \"RESULT: $test_file:\n\")
#                (run-tests $test_case_arg)"
fi
exit
